### ISSUE TITLE
sm64dxcoop merge?

### ISSUE THREAD

**Issue by zqpvr** [robertkirkman/sm64ex-coop#20] opened 2024-07-02 19:38 UTC

**Comment by robertkirkman** [comment] 2024-07-02 20:09
hi i am reading the update, but it is a huge update that will take a long time to read. It also seems there are several bugs introduced in that sm64coopdx 1.0 update that haven't been fixed yet, so by the time i upload any edits to that version, it will have a minor revision i can use to avoid introducing bugs.

**Comment by robertkirkman** [comment] 2024-07-17 00:00
Duplicate of #19

**Closed as completed by robertkirkman** 2024-07-17 00:00 UTC
