### ISSUE TITLE
How To Update Sm64ex Coop Into V37

### ISSUE THREAD

**Issue by CarGamerYoutuber** [robertkirkman/sm64ex-coop#22] opened 2024-07-20 21:28 UTC
**Describe the bug**
Please Update Sm64ex Coop To v37 Because v36.1 Is Outdated 

**Desktop (please complete the following information):**
 - OS: [Magic Os]
 - Browser [Chrome]
 - Version [Android 13]

**Smartphone (please complete the following information):**
 - Device: [Honor x7]
 - OS: [Magic Os 7.1]
 - Browser [Chrome]
 - Version [Android 13]

**Comment by robertkirkman** [comment] 2024-07-20 23:37
Duplicate of #19

**Closed as completed by robertkirkman** 2024-07-20 23:37 UTC

**Comment by CarGamerYoutuber** [comment] 2024-07-21 01:29
Tell Me

**Comment by Aust20156** [comment] 2024-07-28 19:23
How do on tablet? (MODEL: FIRE HD 8 (10th gen) (also my OS is  Fire OS 7.3.2.9)

**Comment by Aust20156** [comment] 2024-07-28 19:25
And my tablet is Android 7/8/9

**Comment by Aust20156** [comment] 2024-08-07 22:18
Response yet?
